services:
  postgres:
    image: postgres:latest
    container_name: pg-graph
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
      - DB_USER=${DB_USER}
      - DB_USER_PW=${DB_USER_PW} 
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - ./config/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./config/00_init.sh:/docker-entrypoint-initdb.d/00_init.sh
      - ./pg-graphdata:/var/lib/postgresql/data

volumes:
  pg-graphdata:
    name: pg-graphdata